window[require('api').file]
	.filter('links',		require('../www/filter/links.js'))
	.filter('max',			require('../www/filter/max.js'))
	.service('socket',		require('../api/service/socket.js'))
	.service('prop',		require('../api/service/prop.js'))
	.service('pay',			require('../shop/service/pay.js'))
	.directive('alert',		require('../api/directive/alert.js'))
	.directive('feedback',	require('../glph/directive/feed.js'))
	.directive('follow',	require('../glph/directive/follow.js'))
	.directive('gateway',	require('../shop/directive/gateway.js'))
	.directive('goNow',		require('../api/directive/goNow.js'))
	.directive('inValue',	require('../api/directive/value.js'))
	.directive('isUnique',	require('../auth/directive/tester.js'))
	.directive('ngEvent',	require('../api/directive/event.js'))
	.directive('ngIcon',	require('../api/directive/icon.js'))
	.directive('ngProgress',require('../api/directive/progress.js'))
	.directive('ngToster',	require('../api/directive/toast.js'))
	.directive('rePass',	require('../auth/directive/repass.js'))
	.directive('right',		require('../api/directive/resize.js'))
	.controller('tables',	require('../shop/controller/table.js'))
	.controller('Crtl',		require('../api/controller/master.js'))
	.controller('Cart',		require('../shop/controller/baucher.js'))
	.controller('download',	require('../shop/controller/down.js'))
	.controller('item',		require('../glph/controller/item.js'))
	.controller('Creator',	require('../auth/controller/maker.js'))
	.config(require('./config.js'))
	.run(require('../api/service/run.js'));