window[require('api').file]
	.service('socket',		require('../api/service/socket.js'))
	.service('prop',		require('../api/service/prop.js'))
	.filter('links',		require('../www/filter/links.js'))
	.filter('max',			require('../www/filter/max.js'))
	.directive('alert',		require('../api/directive/alert.js'))
	.directive('background',require('../glph/directive/background.js'))
	.directive('follow',	require('../glph/directive/follow.js'))
	.directive('goNow',		require('../api/directive/goNow.js'))
	.directive('inValue',	require('../api/directive/value.js'))
	.directive('ngEvent',	require('../api/directive/event.js'))
	.directive('ngIcon',	require('../api/directive/icon.js'))
	.directive('ngId',		require('../www/directive/ngId.js'))
	.directive('ngTabs',	require('../www/directive/tabs.js'))
	.controller('item',		require('../glph/controller/item.js'))
	.controller('all',		require('../import/controller/all.js'))
	.controller('Crtl',		require('../api/controller/master.js'))
	.config(require('./config.js'))
	.run(require('../api/service/run.js'));