require('match-media');
window.angular = require('angular');
require('angular-deckgrid');
require('angular-file-directive');
require('angular-messages');
require('angular-re-captcha');
require('angular-resource');
require('angular-route');
require('angular-sanitize');
require('angular-socket-io');
require('angular-touch');
require('angularjs-viewhead');
require('angulartics');
require('angulartics-google-analytics');
require('ment.io');
require('ng-dialog');
require('ng-infinite-scroll');
require('ngsticky');
require('angular-moment');
window[ require('api').file ] = require('angular').module( require('api').name, require('api').modules );